const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{value:id==='button'?'double':id==='touch-mode'?'trackpad':'',style:{},dataset:{},classList:{toggle(){}},setAttribute(){},setPointerCapture(){},focus(){this.focused=true;},blur(){this.focused=false;},naturalWidth:1920,naturalHeight:1080,clientWidth:960,clientHeight:540,open:false,listeners:{},addEventListener(name,fn){this.listeners[name]=fn;},getBoundingClientRect(){return {left:10,top:20,width:960,height:540};},removeAttribute(){}});return elements.get(id);};
const calls=[];
const context=vm.createContext({window:{addEventListener(){}},document:{body:{classList:{add(){},remove(){}}},documentElement:{},addEventListener(){},getElementById:element,querySelectorAll:()=>[]},URL,AbortSignal,setTimeout,Promise,fetch:async(path,options)=>{calls.push({path,options});return {ok:true,status:200,json:async()=>({ok:true})};}});
const script=fs.readFileSync('windows-host/viewer.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
vm.runInContext(script,context);
(async()=>{
 vm.runInContext('connected=true',context);
 const screen=element('screen');
 screen.listeners.click({clientX:490,clientY:290,currentTarget:screen});
 await vm.runInContext('inputQueue',context);
 assert.equal(calls.length,1);
 assert.deepEqual(JSON.parse(calls[0].options.body),{type:'click',x:0.5,y:0.5,button:'double'});
 assert.equal(calls[0].options.headers['X-DeskFlow'],'1');
 screen.listeners.click({clientX:-10,clientY:290,currentTarget:screen});
 await vm.runInContext('inputQueue',context);assert.equal(calls.length,1);
 element('zoom').listeners.click();assert.equal(screen.style.width,'1920px');assert.equal(screen.style.height,'1080px');
 element('fit').listeners.click();assert.equal(screen.style.width,'960px');assert.equal(screen.style.height,'540px');
 element('viewport').clientWidth=390;element('viewport').clientHeight=844;vm.runInContext('fitDisplay()',context);
 assert.equal(screen.style.width,'390px');assert.equal(screen.style.height,'219.375px');assert.equal(element('stage').style.height,'844px');
 element('tools').open=true;element('hide-tools').listeners.click();assert.equal(element('tools').open,false);
 assert.equal(calls.length,1,'Display/menu actions must not send remote input');
 element('viewport').listeners.pointerdown({pointerType:'touch',isPrimary:true,pointerId:1,clientX:80,clientY:600,preventDefault(){}});
 element('viewport').listeners.pointermove({pointerId:1,clientX:176,clientY:600});
 element('viewport').listeners.pointerup({pointerId:1});await vm.runInContext('inputQueue',context);
 const move=JSON.parse(calls.at(-1).options.body);assert.equal(move.type,'move');assert.equal(move.x,0.6);assert.equal(move.y,0.5);
 element('viewport').listeners.pointerdown({pointerType:'touch',isPrimary:true,pointerId:2,clientX:20,clientY:700,preventDefault(){}});
 element('viewport').listeners.pointerup({pointerId:2});await vm.runInContext('inputQueue',context);
 assert.deepEqual(JSON.parse(calls.at(-1).options.body),{type:'click',x:0.6,y:0.5,button:'double'});
 element('toggle-cursor').listeners.click();assert.equal(element('remote-cursor').hidden,true);
 element('show-keyboard').listeners.click();assert.equal(element('text-entry').focused,true);
 element('text-entry').value='Hello नमस्ते 😀';await element('send-text').listeners.click();
 assert.equal(JSON.parse(calls.at(-1).options.body).text,'Hello नमस्ते 😀');assert.equal(element('text-entry').value,'');
 const total=calls.length;
 vm.runInContext('connected=false',context);
 screen.listeners.click({clientX:490,clientY:290,currentTarget:screen});
 await vm.runInContext('inputQueue',context);assert.equal(calls.length,total);
 console.log('Viewer: normalized coordinates, one request per tap, offscreen rejection, landscape/portrait fit, zoom, hidden controls and disconnected input checks passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
